### ISSUE TITLE
CPU lag during game:

### ISSUE THREAD

**Issue by HumbleTS** [CnCNet/ts-patches#4]
Currently there is no way to check CPU use in game.  Ping and Loss don't always determine who the lagger is.

Ability to force all users to do /CPU command during game, even if only via lobby (on 2nd monitor) would be very helpful.

Ability to kick specs during game?

**Comment by FunkyFr3sh** [comment]
It keeps track of cpu lag since last update, there will be warning about low FPS players before the game starts. I fear people will ignore it though, they often start games with 1000ms ping players and then wonder why it lags :P 

Kicking specs during game is possible in red alert already, should be possible to port that to tiberian sun too I guess.

**Comment by HumbleTS** [comment]
I think dkeeton said the FPS for TS is around 45, I suggest changing that to 52.  If their PC can't support at least 52, it's not worth playing with them TBH.  Anything much off from 56 is miserable in a high micro intense game.

**Comment by HumbleTS** [comment]
(Maybe suggest or automatically force said user running below average 50-52 FPS to a lower resolution or something)
